version: 0.0
os: linux

files:
  - source: /
    destination: /Django_Chatapp
    file_exists_behavior: OVERWRITE
    
hooks:
  BeforeInstall:
    - location: scripts/Env_requirements.sh
      runas: ubuntu

  ApplicationStart:
    - location: scripts/Restart_Migration.sh
      runas: ubuntu
