version: 0.0
os: linux

files:
  - source: /
    destination: /Django_Chatapp
    file_exists_behavior: OVERWRITE
    
hooks:
  BeforeInstall:
    - location: Django_Chatapp/scripts/Env_requirements.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: Django_Chatapp/scripts/Env_requirements.sh
      timeout: 300
      runas: ubuntu
