version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing system dependencies..."
      - apt-get update && apt-get install -y libpq-dev python3-dev
      - echo "Installing Python dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Setting working directory..."
      - cd /codebuild/output/src3869147683/src/fundoo  # Adjust this path to match your project structure
      - echo "Running migrations..."
      - python manage.py migrate
      - echo "Collecting static files..."
      - python manage.py collectstatic --noinput

artifacts:
  files:
    - '**/*'
  discard-paths: no
