version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo ">>> Installing dependencies..."
      - python3 -m venv venv  # Create virtual environment
      - bash -c "source venv/bin/activate && pip3 install -r requirements.txt"

  build:
    commands:
      - echo ">>> Running tests..."

  post_build:
    commands:
      - echo ">>> Packaging the app for deployment..."
      - zip -r Django_Chatapp.zip . -x "venv/*" "*.git/*"

artifacts:
  files:
    - appspec.yml
    - Django_Chatapp.zip
  discard-paths: no
